### ISSUE TITLE
Source code and Unity 3.5 compatible.

### ISSUE THREAD

**Issue by favoyang** [Countly/countly-sdk-unity#1]
Can you provide source code directly, rather than a unitypackage? Then we can track file version. Also the current provided unitpackage is not 3.5 compatible.

You can leave unitypackage as a release format in asset strore.

**Comment by hupptech** [comment]
Hi There,

We've structured our code for you to easily use it. Added documents too for you to easily understand and add it to your project.

Thanks for feedback.
