### ISSUE TITLE
Error building Player on Android

### ISSUE THREAD

**Issue by shadow0162** [Countly/countly-sdk-unity#10]
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Applications/adt/sdk/build-tools/android-4.2.2/aapt package --auto-add-overlay -v -f -m -  J gen -M AndroidManifest.xml -S "res" -I "/Applications/adt/sdk/platforms/android-  19/android.jar" -F bin/resources.ap_

stderr[
AndroidManifest.xml:21: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').
]

**Comment by hupptech** [comment]
I'll suggest that you review our documentation here : https://github.com/Countly/countly-sdk-unity/tree/master/docs

If you didn't add Google Play Services library into your project, you
should add it also. Do next steps for it:

First of all, you should be sure you don't have this library in your
project. Some another plugins can use this library also. If you
already included this library, you shouldn't add it twice.
Copy unity/Assets/Plugins/Android/libs/google-play-services.jar into
your Assets/Plugins/Android/libs directory of your project. If you
have not this directory you should create it.
Copy unity/Assets/Plugins/Android/res folder into your
Assets/Plugins/Android/ folder. So you will have
Assets/Plugins/Android/res folder with couple of folders inside this
res folder.

If you didn't add Google Support Library into your project, you should
add it. Do next steps for it:

First of all, you should be sure you don't have this library in your
project. Some another plugins can use this library also. If you
already included this library, you shouldn't add it twice.
Copy unity/Assets/Plugins/Android/libs/android-support-v4.jar into
your Assets/Plugins/Android/libs directory of your project. If you
have not this directory you should create it.

Important! Check twice your libraries. If you already included some
lib, and if that lib is included again then your project will have compile errors
when you will compile it to Android.

**Comment by shadow0162** [comment]
Thanks.it's work.

**Comment by hupptech** [comment]
Great. I'll close this issue for now.
