### ISSUE TITLE
SDK production ready?

### ISSUE THREAD

**Issue by hivearts** [Countly/countly-sdk-unity#12]
Hello,

I would like to buy enterprise edition of countly, so i wonder are this SDK supported by unity 2018, if it is, is there any limitations on it? For example push notifications not works, etc..

Thanks,
Goran

**Comment by gorkem-cetin** [comment]
Hi Goran - almost ready and this repo will be updated very soon. I have sent you a personal email on the same subject. Closing this issue for now and let's discuss via email.
