### ISSUE TITLE
Unlimited errors in CountlyEntryPoint in latest version

### ISSUE THREAD

**Issue by ajeets1978** [Countly/countly-sdk-unity#127]
Using Unity Version 2018.4.30f1

Had this been tested with this version of unity.

`Assets/Plugins/CountlySDK/Countly.cs(230,21): error CS1644: Feature `asynchronous functions' cannot be used because it is not part of the C# 4.0 language specification`

Millions of such error in each .CS

`Tasks` in import doesn't exist in System.Threading namespace

**Comment by ZahidZafar** [comment]
Hello,
Our Unity SDK is targeting the .NET 4.x runtime. Therefore it would be incompatible with projects that are targeting .NET 3.5.
To solve those build errors, you would go to project build setting and change the 'Scripting runtime version' to .NET 4.x.
Thanks.
