### ISSUE TITLE
This package really makes itself home

### ISSUE THREAD

**Issue by AldeRoberge** [Countly/countly-sdk-unity#198]
Warn your users to NOT import this .unitypackage into their working projects, as this will import files all over the place.

Instead of neatly placing itself into the Plugins/Countly folder like all well-behaved plugins do, this unity package will instead bits and pieces of junk all over your project, including but not limited to :

* The root of your assets folder
* Inside the Plugins folder
* Inside a subfolder named Android and iOS IN the Plugins folder but OUT of the Countly folder
* Adds a neat little csc.rsp file

Please simply aggregate all of your SDK files required to make this work into a simple, neat folder to avoid the headaches of figuring out why importing this broke the hell loose in my project.

![image](https://github.com/Countly/countly-sdk-unity/assets/4276275/56924827-0807-41c9-9535-f531953c6540)

Thankfully, I was using a dummy project to test and had a VCS enabled.

**Comment by AldeRoberge** [comment]
Maybe I was a bit harsh here, but clearly the person(s) who made this integration into Unity never actually opened it in their projects. Again the solution is very simple : Move all of your junk files into a subfolder to hide it away and to avoid it mixing with all of your other plugins.

**Comment by AldeRoberge** [comment]
Digging deeper into the problem this caused in my project, it was due to a .asmdef file at the root of the Plugins folder :
![image](https://github.com/Countly/countly-sdk-unity/assets/4276275/1bca310c-a62e-49f4-97ef-c46c19b64d79)

**Comment by AliRKat** [comment]
Hello,
Thank you for the feedback and for mentioning these points. We will examine these issues and look into shifting the structure within the next release.

**Comment by AliRKat** [comment]
Hello, our minor release which contains the shifted structure is out. Feel free to check it out!
[https://github.com/Countly/countly-sdk-unity/releases/tag/23.12.1](url)
