### ISSUE TITLE
Fail to build Unity 2018.4.1f1  error merging dex

### ISSUE THREAD

**Issue by imtrobin** [Countly/countly-sdk-unity#20]
Reporting, using the sample in the sdk to build to Android on windows, it will fail with Error merging dex archives.

**Comment by gorkem-cetin** [comment]
Can you provide more information on:

1) What you have done, step by step
2) Your environment
3) Any logs if possible

**Comment by imtrobin** [comment]
Repro
1. Open countly-sdk-unity in Unity 2018.1.4 (windows 10)
2. Switch to Android. Set package name.
3. Build

**Comment by imtrobin** [comment]
![1](https://user-images.githubusercontent.com/531606/59144909-287e0200-8a0f-11e9-8a84-6572c700caa2.jpg)
![2](https://user-images.githubusercontent.com/531606/59144910-2a47c580-8a0f-11e9-85af-7f1e539b6a48.jpg)

**Comment by ArtursKadikis** [comment]
This shouldn't be an issue anymore
