### ISSUE TITLE
Fail to build Unity 2018.3.14f1

### ISSUE THREAD

**Issue by tuanit09** [Countly/countly-sdk-unity#24]
Here is the error details:
`CommandInvokationFailure: Gradle build failed. 
/Applications/Unity/Hub/Editor/2018.3.14f1/PlaybackEngines/AndroidPlayer/Tools/OpenJDK/MacOS/bin/java -classpath "/Applications/Unity/Hub/Editor/2018.3.14f1/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
D8: Program type already present: com.playdarium.services.notifications.RemoteNotificationsService

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/0.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/1.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/2.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/3.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/4.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/5.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/6.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/7.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/8.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/9.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/10.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/12.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/13.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/14.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/15.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/16.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/17.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/18.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/19.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/20.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/21.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/22.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/23.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/24.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/25.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/26.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/27.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/28.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/29.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/30.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/31.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/32.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/33.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/34.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/35.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/36.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/37.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/39.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/40.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/41.jar, /Volumes/Data/_Repositories/Swissarena/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/42.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.playdarium.services.notifications.RemoteNotificationsService

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
]`

**Comment by ArtursKadikis** [comment]
Hello, how did you get this error? What did you do?

**Comment by tuanit09** [comment]
@ArtursKadikis

We have an existing Unity project and we wanted to integrate Countly. The first time we did this was April 1st, 2019 and the build was ok. We have issue with tracking views though (question posted but no answer till now: https://community.count.ly/t/unity3d-reported-views-are-not-shown-in-user-profile/695)

This time, we saw that the Countly SDK has been updated (we hope this could solve our issue above). We apply the same (quite same but not exact) process to integrate the SDK but we failed to build APK. We followed the guide here https://resources.count.ly/docs/countly-sdk-for-unity and also the REDME of this repo.

**Comment by nazgull30** [comment]
Hi, @tuanit09,

Documentation [here](https://resources.count.ly/docs/countly-sdk-for-unity) is a bit deprecated. If you have old version of Countly SDK then it would be better if you remove it entirely. Also, take a look at project settings, they are extremely important. 
You need to use file mainTemplate.
Documentation is on [github](https://github.com/countly/countly-sdk-unity). Section "How to set up the project".

New version of countly plugin does not use neither  firebase unity plugin nor Android Resolver libraries. So you can remove all aar or jar files from Plugins/Android folder related to countly.

**Comment by ArtursKadikis** [comment]
This shouldn't be an issue anymore
