### ISSUE TITLE
Debug.log spam

### ISSUE THREAD

**Issue by EmyEdoki** [Countly/countly-sdk-unity#39]
Hello we recently update our countly sdk and it now spamming our console with a lot of Debug.log

One each time we report an event
One each time we report a view event
One on application focus: false
One on application focus: true
One on application quit

It would be very simple to wrap them in a CountlyLog function that can be toggle in the parameter.

**Comment by ArtursKadikis** [comment]
Hello, this is already a thing we are fixing. Such a flag will be available in the next version we will release. The release will happen in 1 or 2 weeks

**Comment by EmyEdoki** [comment]
Thanks

**Comment by EmyEdoki** [comment]
Hello thanks for fixing this issue bug we are using the branche no push because we can't use firebase. I try to do a simple merge from master but all firebase thing are merge with it. Could you update the branch no push?

**Comment by ArtursKadikis** [comment]
To remove the push dependencies you would follow these steps:
https://support.count.ly/hc/en-us/articles/360037813851-Unity#remove-fcm-dependencies

The "no_push" branch was meant as a temporary measure.
