### ISSUE TITLE
How to actually install this?

### ISSUE THREAD

**Issue by peterwilli** [Countly/countly-sdk-unity#7]
Hi,

I tried to update to the latest Countly SDK.
Previously I could get a unitypackage and just import it.

Right now there is just a bunch of folders and that's really hard to copy to a unity project without replacing unwanted folders and files. 

On here: http://resources.count.ly/docs/countly-sdk-for-unity they just say 'Import Countly SDK into your project', which is not easy to follow.

What happened to the unity package? What are the correct instructions? Thanks!

**Comment by hupptech** [comment]
Hello Peter,
We'll restructure the files and update our read.me, with more details on how you can integrate this. Thanks for patience.

**Comment by hupptech** [comment]
Hi Peter,
We've just updated our SDK and made a very detailed document on how you can use it in your app.
Try it and let us know if you still have issues.

**Comment by peterwilli** [comment]
Thanks that worked!
